[package]
name = "cv"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
tokio = { version = "1" }
minijinja = { version = "2.9.0", features = ["loader", ] }
minijinja-autoreload = "2.9.0"

derive_more = "2.0.1"

log = "0.4.27"
env_logger = "0.11.8"
